fail_fast: true

default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-imports
        args:
          - "-w"
      - id: go-mod-tidy
      - id: go-sec-repo-mod

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.51.1
    hooks:
      - id: golangci-lint
        args:
          - "--timeout=3m"
          - "--enable=gocritic"

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.24.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
