# Sample configuration file tailored to work with Docker

serverPort: 3128

backend: http://backend:8080

rules:
  - method: POST
    pathPattern: ^\/health$
    requestPerSecond: 1
    burst: 2
  - method: POST
    pathPattern: ^\/some*.$
    requestPerSecond: 1
    burst: 2
