serverPort: 8080
basePath: /dev
defaultBackend: backend0

backends:
  - name: backend0
    url: http://127.0.0.1:8081

rules:
  - pathPrefix: /api/events
    requestPerSecond: 1
    burst: 2
  - pathPrefix: /
    requestPerSecond: 1
    burst: 2
