version: "3.6"
services:
  prod:
    image: dhis2/go-rate-limit:${IMAGE_TAG:-latest}
    build: .
    ports:
      - "8080:3128"
    volumes:
      - ./config.yml:/app/config.yml
    depends_on:
      - backend

  test:
    build:
      context: .
      target: build
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/sh -c 'go test -v ./test'

  dev:
    build:
      context: .
      target: build
    ports:
      - "8080:3128"
    volumes:
      - .:/src
    command: reflex -r "\.go|\.yml$$" -s -- sh -c "go run ./cmd/go-rate-limit"
    depends_on:
      - backend

  backend:
    image: tons/whoami-go:0.4.0
