x-service: &common-dev-test
  build:
    context: .
    target: build
  volumes:
    - .:/src
  working_dir: /src

version: "3.6"
services:
  prod:
    image: dhis2/go-api-gateway:${IMAGE_TAG:-latest}
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./config.yml:/app/config.yml
    depends_on:
      - backend0
      - backend1

  test:
    <<: *common-dev-test
    command: /bin/sh -c 'go test -v ./...'

  dev-test:
    <<: *common-dev-test
    command: reflex -r "\.go|\.yml$$" -s -- sh -c "go test -v ./..."

  dev:
    <<: *common-dev-test
    ports:
      - "8080:8080"
    command: reflex -r "\.go|\.yml$$" -s -- sh -c "go run ./cmd/serve"

  backend0:
    image: tons/whoami-go:0.5.0

  backend1:
    image: tons/whoami-go:0.5.0
