apiVersion: skaffold/v2beta25
kind: Config
build:
  artifacts:
    - image: dhis2/go-api-gateway
deploy:
  statusCheckDeadlineSeconds: 120
  helm:
    releases:
      - name: go-api-gateway-{{ .ENVIRONMENT }}
        namespace: instance-manager-{{ .ENVIRONMENT }}
        createNamespace: true
        chartPath: helm/chart
        artifactOverrides:
          image: dhis2/go-api-gateway
        imageStrategy:
          helm: { }
        useHelmSecrets: true
        valuesFiles:
          - helm/data/values/{{ .ENVIRONMENT }}/values.yaml
