// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package di

import (
	"github.com/dhis2-sre/go-rate-limiter/pgk/config"
	"github.com/dhis2-sre/go-rate-limiter/pgk/handler"
	"github.com/dhis2-sre/go-rate-limiter/pgk/rule"
	"log"
	"net/http"
)

// Injectors from wire.go:

func GetApplication() Application {
	config := provideConfigWithoutError()
	router := rule.ProvideRouter(config)
	handlerFunc := handler.ProvideHandler(config, router)
	application := ProvideApplication(config, handlerFunc)
	return application
}

// wire.go:

type Application struct {
	Config  *config.Config
	Handler http.HandlerFunc
}

func ProvideApplication(c *config.Config, h http.HandlerFunc) Application {
	return Application{c, h}
}

func provideConfigWithoutError() *config.Config {
	c, err := config.ProvideConfig()
	if err != nil {
		log.Fatal(err)
	}
	return c
}
