apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-gateway.fullname" . }}
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
data:
  config.yml: |-
    {{- toYaml .Values.configuration | nindent 4 }}
